/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 *
 * `yarn passport:bootstrap` (or `yarn hardhat:deploy --network hederaTestnet`)
 * regenerates it with the deployed PassportRegistry. Until then it is empty, so
 * the app builds and the Debug Contracts page reports "No contracts found!".
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
