/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    PassportRegistry: {
      address: "0xCBc3089cb39ef55114341Ff1aB9BFeA5f22D5a7A",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOwner",
              type: "address",
            },
            {
              internalType: "address",
              name: "htsAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AlreadyHolder",
          type: "error",
        },
        {
          inputs: [],
          name: "CollectionAlreadyCreated",
          type: "error",
        },
        {
          inputs: [],
          name: "CollectionNotCreated",
          type: "error",
        },
        {
          inputs: [],
          name: "EmptyField",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "HtsCreateFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "HtsMintFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "HtsTransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidProductHash",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidRecipient",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidTopicId",
          type: "error",
        },
        {
          inputs: [],
          name: "MetadataTooLong",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              internalType: "address",
              name: "holder",
              type: "address",
            },
          ],
          name: "NotHolder",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "NotIssuer",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              internalType: "address",
              name: "holder",
              type: "address",
            },
          ],
          name: "NotTreasuryHeld",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
          ],
          name: "ProductNotFound",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "UnexpectedSerialCount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "collection",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "symbol",
              type: "string",
            },
          ],
          name: "CollectionCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "CustodyTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "allowed",
              type: "bool",
            },
          ],
          name: "EventLoggerSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "allowed",
              type: "bool",
            },
          ],
          name: "IssuerSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "PassportAirdropped",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              indexed: false,
              internalType: "string",
              name: "topicId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "productHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
          ],
          name: "ProductRegistered",
          type: "event",
        },
        {
          inputs: [],
          name: "AUTO_RENEW_PERIOD",
          outputs: [
            {
              internalType: "int64",
              name: "",
              type: "int64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "COLLECTION_MEMO",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DEFAULT_HTS",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "HTS",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "METADATA_MAX_BYTES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SUCCESS",
          outputs: [
            {
              internalType: "int64",
              name: "",
              type: "int64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SUPPLY_KEY",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TOPIC_ID_MAX_BYTES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "airdropPassport",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "collection",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
          ],
          name: "createCollection",
          outputs: [
            {
              internalType: "address",
              name: "createdAddress",
              type: "address",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
          ],
          name: "currentHolder",
          outputs: [
            {
              internalType: "address",
              name: "holder",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
          ],
          name: "getProduct",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "topicId",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "productHash",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "issuer",
                  type: "address",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct PassportRegistry.Product",
              name: "product",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "isEventLogger",
          outputs: [
            {
              internalType: "bool",
              name: "allowed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "isIssuer",
          outputs: [
            {
              internalType: "bool",
              name: "allowed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "productCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "metadata",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "productHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "topicId",
              type: "string",
            },
          ],
          name: "registerProduct",
          outputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "bool",
              name: "allowed",
              type: "bool",
            },
          ],
          name: "setEventLogger",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "bool",
              name: "allowed",
              type: "bool",
            },
          ],
          name: "setIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "serial",
              type: "int64",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "transferCustody",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        owner: "@openzeppelin/contracts/access/Ownable.sol",
        renounceOwnership: "@openzeppelin/contracts/access/Ownable.sol",
        transferOwnership: "@openzeppelin/contracts/access/Ownable.sol",
      },
      deployedOnBlock: 40801009,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
